global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'banking-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']
        labels:
          service: 'banking-app'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
